### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jorbush** [jorbush/toMime#4]
- [ ] #2 
- [ ] #3 
- [ ] Clean code `Game`
- [ ] Cannot swipe card before flipping it over
- [ ] Polishing the form visually
- [ ] Scrollable column in the form
- [ ] advanced settings form new game
- [ ] Reimagining the home screen
- [ ] GAME MODES and COLLECTIONS as Advanced Settings and that they are somehow hidden and are unoccupied with a cool animation [Form]
- [ ] error control and display them on the screen [Form]
- [ ] Provider collections
- [ ] Card packs store
- [ ] Login and User Authentication
- [ ] Integration with Firebase (Collection)
- [ ] ThemeData y routes (`main.dart`)
- [ ] Set time [Form]
- [ ] Select collections [Form]
- [ ] Round selector (1, 2, 3, 4 or 5 rounds) this option is available depending on the selected Collections (basically because if there are not many cards you can't make many rounds) [Form]
- [ ] When backing out during the Game `AlertDialog (“Are you sure?”)`
- [ ] `Alertdialog` when pop in game and `end.dart` is not possible to back out (willpop may work)
- [ ] Landscape mode in all the app. In the `GAME` the points and the player on the right, the cards in the middle and on the left the remaining time.
- [ ] 10 players to have a cool random avatar (generate 10 with dal-le)
- [ ] Language [Settings]
- [ ] Settings language save using sqlite (locally)
- [ ] Implement with sqllite that you can save and retrieve lists of recurring players. Save in `End.dart` (who have played the game, make a form that comes out from below, personal expenses type, with the name for the list) and can be loaded in `form.dart` (put an emoticon)
- [ ] Generate new_pack (20)
- [ ] Generate rythm_music pack (20)
- [ ] Firebase Cloud Messaging
- [ ] Have the application read the name of the player whose turn it is to play [GAME]
